<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**
CS6501 - MACHINE LEARNING AND APPLICATIONS 

###Instructor: Enrique Naredo
###CS6501_Lab-0.15_sol

#**Extra Numpy problems**

In [1]:
import numpy as np

## Problem 21

Import the [iris dataset](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) and compute the [softmax score](https://en.wikipedia.org/wiki/Softmax_function) of `sepallength`.

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

## Problem 22

Replace all ocurrences of `nan` with 0 in numpy array.

Input:

`url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'`

`iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])`

`iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan`

In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d)
print("\n\n")
iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 nan 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 nan 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 nan]
 [nan 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 nan]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 nan 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 nan]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Problem 23

Find the unique values and the count of unique values in iris's `species`.

Input:

`url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'`

`iris = np.genfromtxt(url, delimiter=',', dtype='object')`

`names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')`

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', usecols=[4])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(np.unique(iris))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


## Problem 24

Randomly sample iris's `species` such that `setose` is twice the number of `versicolor` and `virginica`.

Input:

`url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'`

`iris = np.genfromtxt(url, delimiter=',', dtype='object')`

In [7]:
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
print
print(np.random.choice(a, 150, p=[0.5, 0.25, 0.25]))

['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor

## Problem 25

Find the value of second longest petallength of species setosa.

Input:

`url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'`

`iris = np.genfromtxt(url, delimiter=',', dtype='object')`

In [10]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
m1 = m2 = iris[0,2] 
for i in iris[:,2]:
  if i > m1:
    m2 = m1
    m1 = i
print(m1)
print(m2)
  

b'6.9'
b'6.7'


## Problem 26

Sort the iris dataset based on `sepallength` column.

Input:

`url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'`

`iris = np.genfromtxt(url, delimiter=',', dtype='object')`

`names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')`

In [12]:
iris[iris[:,0].argsort()]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4

## Problem 27

Find the most frequent value of `petallength` (3rd column) in iris dataset.

Input:

`url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'`

`iris = np.genfromtxt(url, delimiter=',', dtype='object')`

`names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')`

In [16]:
from scipy import stats
m = stats.mode(iris[:,2])
print(m.mode[0])

b'1.5'


## Problem 28

Find the position of the first occurrence of a value greater than 1.0 in `petalwidth` 4th column of iris dataset.

Input:

`url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'`

`iris = np.genfromtxt(url, delimiter=',', dtype='object')`

`names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')`


In [30]:
j = np.argmax(iris[:,3] > b'1')
print(iris[:j+1,3])
print(j)

[b'0.2' b'0.2' b'0.2' b'0.2' b'0.2' b'0.4' b'0.3' b'0.2' b'0.2' b'0.1'
 b'0.2' b'0.2' b'0.1' b'0.1' b'0.2' b'0.4' b'0.4' b'0.3' b'0.3' b'0.3'
 b'0.2' b'0.4' b'0.2' b'0.5' b'0.2' b'0.2' b'0.4' b'0.2' b'0.2' b'0.2'
 b'0.2' b'0.4' b'0.1' b'0.2' b'0.1' b'0.2' b'0.2' b'0.1' b'0.2' b'0.2'
 b'0.3' b'0.3' b'0.2' b'0.6' b'0.4' b'0.3' b'0.2' b'0.2' b'0.2' b'0.2'
 b'1.4']
50


## Problem 29

From the array `a`, replace all values greater than 30 to 30 and less than 10 to 10.

Input:

`np.random.seed(100)`

`a = np.random.uniform(1,50, 20)`


In [32]:
np.random.seed(100)

a = np.random.uniform(1,50, 20)
print(a)
print("\n\n")
a[(a>30)] = 30
a[(a<10)] = 10
print(a)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]



[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


## Problem 30

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

Input:

`np.random.seed(100)`

`a = np.random.randint(0, 5, 10)`

In [44]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
d = {}
print(a)
for i in range(len(a)):
  if a[i] in d:
    a[i] = True
    continue
  d[a[i]] = 1
  a[i] = False
print(a)

[0 0 3 0 2 4 2 2 2 2]
[0 1 0 1 0 0 1 1 1 1]
