<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**
CS6501 - MACHINE LEARNING AND APPLICATIONS 

###Instructor: Enrique Naredo
###CS6501_Lab-0.13_sol

#**Extra Numpy problems**

## Problem 1 

Import numpy as np and print the version number.

In [1]:
import numpy as np
print(np.__version__)

1.19.5


## Problem 2

Create a 3×3 numpy array of all True’s

In [3]:
np.array([True for _ in range(9)]).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Problem 3

Extract all odd numbers from a 1D array

In [7]:
a=np.random.randint(1,30,10)
print(a)
a[a%2==1]

[ 4 20 16 24 20 25  5 28 18 27]


array([25,  5, 27])

## Problem 4

Replace all odd numbers in a 1D array with -1

In [9]:
a=np.random.randint(1,30,10)
print(a)
a[a%2==1] = -1
print(a)

[ 3 28 16 13 25 10  7  4  8 10]
[-1 28 16 -1 -1 10 -1  4  8 10]


## Problem 5

Convert a 1D array to a 2D array with 2 rows

In [11]:
a=np.random.randint(1,30,10)
print(a)
print(a.reshape(2,5))


[25  9 21 15  5 28  9 24 25 15]
[[25  9 21 15  5]
 [28  9 24 25 15]]


## Problem 6

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

`a = np.array([1,2,3])`

Desired Output:

`array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [16]:
a = np.array([1,2,3])
np.concatenate((np.repeat(a,3), np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## Problem 7

Get the common items between a and b

Input:

`a = np.array([1,2,3,2,3,4,3,4,5,6])`

`b = np.array([7,2,10,2,7,4,9,4,9,8])`

Desired Output:

`array([2, 4])`

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## Problem 8

From array a remove all items present in array b

Input:

`a = np.array([1,2,3,4,5])`

`b = np.array([5,6,7,8,9])`

Desired Output:

`array([1,2,3,4])`

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

## Problem 9

Get the positions where elements of a and b match

Input:

`a = np.array([1,2,3,2,3,4,3,4,5,6])`

`b = np.array([7,2,10,2,7,4,9,4,9,8])`

Desired Output:

`(array([1, 3, 5, 7]),)`

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

## Problem 10

Get all items between 5 and 10 from a.

Input:

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

Desired Output:

`array([6, 9, 10])`

In [24]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a<=10) & (a>=5)]

array([ 6,  9, 10])