<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**
CS6501 - MACHINE LEARNING AND APPLICATIONS 

###Instructor: Enrique Naredo
###CS6501_Lab-0.14_sol

#**Extra Numpy problems**

In [1]:
import numpy as np

## Problem 11

Convert the function `maxx` that works on two scalars, to work on two arrays.

    def maxx(x, y):
     #Get the maximum of two items
     if x >= y:
        return x
     else:
         return y

Input:

`a = np.array([5, 7, 9, 8, 6, 4, 5])`

`b = np.array([6, 3, 4, 8, 9, 7, 1])`

Desired Output:

`array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])`

In [2]:
def maxx(x, y):
  for i in range(len(x)):
    yield max(x[i],y[i])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
list(maxx(a,b))

[6, 7, 9, 8, 9, 7, 5]

## Problem 12

Swap columns 0 and 1 in the array `arr`.

Input:

`arr = np.arange(9).reshape(3,3)`

Desired Output:

`array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])`

In [10]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


## Problem 13

Swap rows 0 and 1 in the array `arr`.

Input:

`arr = np.arange(9).reshape(3,3)`

Desired Output:

`array([[3, 4, 5],
        [0, 1, 2],
        [6, 7, 8]])`

In [11]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[0,1],:] = arr[[1,0],:]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


## Problem 14

Reverse the rows of a 2D array `arr`.

Input:

`arr = np.arange(9).reshape(3,3)`

Desired Output:

`array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])`

In [15]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.flip(arr,0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


## Problem 15

Reverse the columns of a 2D array `arr`.

Input:

`arr = np.arange(9).reshape(3,3)`

Desired Output:

`array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])`


In [21]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.flip(arr,1))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Problem 16

Print or show only 3 decimal places of the numpy array `rand_arr`.

Input:

`rand_arr = np.random.random((5,3))`


In [2]:
import numpy as np
rand_arr = np.random.random((5,3))
print(rand_arr)
np.set_printoptions(precision=3)
print(rand_arr)

[[0.97263245 0.78744011 0.09616032]
 [0.88218788 0.66553831 0.14011971]
 [0.3685998  0.27327027 0.73967115]
 [0.82035745 0.71684624 0.55663756]
 [0.8194178  0.17310246 0.99658398]]
[[0.973 0.787 0.096]
 [0.882 0.666 0.14 ]
 [0.369 0.273 0.74 ]
 [0.82  0.717 0.557]
 [0.819 0.173 0.997]]


## Problem 17

Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Input:

`a = np.arange(15)`

Desired Output:

`array([ 0,  1,  2, ..., 12, 13, 14])`


In [3]:
a = np.arange(15)
np.set_printoptions(threshold=6)

print(a)

[ 0  1  2 ... 12 13 14]


## Problem 18

Import the [iris dataset](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) with numbers and texts keeping the text intact in Numpy.

In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

## Problem 19

Find the mean, median, standard deviation of iris's `sepallength` (1st column)

In [19]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(np.mean(sepallength))
print(np.median(sepallength))
print(np.std(sepallength))

5.843333333333334
5.8
0.8253012917851409


## Problem 20

Create a normalized form of iris's `sepallength` whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.


In [20]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)

[0.222 0.167 0.111 ... 0.611 0.528 0.444]
