<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**
CS6501 - MACHINE LEARNING AND APPLICATIONS 

###Instructor: Enrique Naredo
###CS6501_Lab-0.6

# Numpy


This part focuses on Numpy, see <a href="https://numpy.org/doc/stable/user/quickstart.html">numpy quickstart tutorial</a>, which I encourage you to reference throughout the course.


Some problems about numpy



# Problem 1 

Create a null vector of size 10 (that is a vector that includes 10 zeros) and print it

In [1]:
#solution
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Problem 2
Create a null vector of size 10 but the fifth value which is 1 

In [2]:
import numpy as np
z = np.zeros(10)
z[5]=1
z

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# Problem 3
Create a vector with all integer values ranging from 10 to 49.

Hint

    You can use a loop with range(10,49)

In [4]:
np.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Problem 4
 Create a 3x3 matrix with values ranging from 0 to 8 

In [5]:
np.array([list(range(0,3)),list(range(3,6)),list(range(6,9))],np.int32)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

# Problem 5
Create a 3x3x3 array with random values.

Hint

    You can use np.random.random

In [6]:
import numpy as np
np.array([[np.random.random() for _ in range(3)] for _ in range(3)])

array([[0.79783118, 0.60856222, 0.61172733],
       [0.55402406, 0.42971858, 0.68110019],
       [0.91430232, 0.00659929, 0.40011361]])