<div>
<img src="https://drive.google.com/uc?export=view&id=1vK33e_EqaHgBHcbRV_m38hx6IkG0blK_" width="350"/>
</div> 

#**Artificial Intelligence - MSc**
CS6501 - MACHINE LEARNING AND APPLICATIONS 

###Instructor: Enrique Naredo
###CS6501_Lab-0.8

# Numpy


This part focuses on Numpy, see <a href="https://numpy.org/doc/stable/user/quickstart.html">numpy quickstart tutorial</a>, which I encourage you to reference throughout the course.


Some problems about numpy



# Problem 11
Normalize a 5x5 random matrix

Solution:
>Z = np.random.random((5,5))
>
>Z = (Z - np.mean (Z)) / (np.std (Z))
>
>print(Z)


In [3]:

import numpy as np
Z = np.random.random((5,5))
print(Z)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


[[0.79450337 0.08224146 0.11508355 0.14187363 0.19067001]
 [0.68526298 0.71993467 0.08451014 0.23030767 0.98127032]
 [0.26117157 0.77094426 0.92671867 0.46243187 0.33992521]
 [0.99768842 0.78821658 0.2496068  0.80035459 0.12110146]
 [0.35125903 0.73635392 0.35926612 0.3961895  0.69384672]]
[[ 0.99898183 -1.34720197 -1.23902043 -1.15077417 -0.99003936]
 [ 0.63914504  0.75335326 -1.33972895 -0.8594733   1.61419033]
 [-0.75780792  0.92137836  1.43449774 -0.09485845 -0.4983942 ]
 [ 1.6682714   0.9782732  -0.79590215  1.01825568 -1.2191975 ]
 [-0.46106069  0.80743812 -0.43468544 -0.31306019  0.66741979]]


# Problem 12

Multiply a 5x3 matrix by a 3x2 matrix (matrix product).

Hint

    It is straightforward if you use np.matmul().

In [8]:
import numpy as np
a=np.arange(2,17).reshape(5,3)
b=np.arange(20,26).reshape(3,2)
np.matmul(a,b)

array([[ 202,  211],
       [ 400,  418],
       [ 598,  625],
       [ 796,  832],
       [ 994, 1039]])

# Problem 13
Given a 1D array, negate in place all elements which are between 3 and 8.

In [13]:
a=np.arange(10)
a[(a>3) & (a<8)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

# Problem 14
How to find common values between two arrays?


In [16]:
a=np.arange(12)
b=np.arange(8,16)
print(np.intersect1d(a,b))

[ 8  9 10 11]


# Problem 15
How to find the most frequent value in an array? (Use `Z = np.random.randint(0,10,50)` to generate the array)

In [27]:
Z = np.random.randint(0,10,50)
from scipy import stats
print(Z)
print((stats.mode(Z))[0][0])
print((np.bincount(Z)).argmax())

[7 3 8 6 0 3 7 1 8 5 9 5 6 6 7 0 5 6 0 4 2 0 9 3 4 5 2 3 3 7 7 9 7 2 9 0 7
 4 0 4 7 3 6 8 6 6 7 1 2 0]
7
7
